services:
  postgres:
    image: postgres:16
    container_name: payflow-postgres
    environment:
      POSTGRES_USER: payflow
      POSTGRES_PASSWORD: payflow
      POSTGRES_DB: payflow_default
    ports:
      - "5432:5432"
    volumes:
      - payflow_postgres_data:/var/lib/postgresql/data
      - ./infrastructure/docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  payflow_postgres_data: